const data = {
  products: [
    {
      _id: 1,
      name: 'Copper peptides 1%',
      image: 'images/copper.jpg',
      slug: 'copper-peptides',
      inStockQuantity: 100,
      description: '30ml',
      price: 30.99,
    },

    {
      _id: 2,
      name: 'Granactive Retinoid 5%',
      image: 'images/granactive.jpg',
      slug: 'granactive-retinoid',
      inStockQuantity: 100,
      description: '30ml',
      price: 16.99,
    },
    {
      _id: 3,
      name: 'Hyaluronic Acid 2% + B5',
      image: 'images/hyaluronic.jpg',
      slug: 'hyaluronic-acid',
      inStockQuantity: 100,
      description: '60ml',
      price: 15.75,
    },
    {
      _id: 4,
      name: 'Virgin Marula Oil',
      image: 'images/marula.jpg',
      slug: 'virgin-maular-oil',
      inStockQuantity: 100,
      description: '30ml',
      price: 11.25,
    },
    {
      _id: 5,
      name: 'HA Moisturizer',
      image: 'images/HAmoisturizer.jpg',
      slug: 'ha-moisturizer',
      inStockQuantity: 100,
      description: '100ml',
      price: 13.59,
    },
    {
      _id: 6,
      name: 'Vitamin C Moisturizer',
      image: 'images/VCmoisturizer.jpg',
      inStockQuantity: 100,
      slug: 'vitamin-c-moisturizer',
      description: '100ml',
      price: 19.99,
    },
    {
      _id: 7,
      name: 'Squalane Cleanser%',
      image: 'images/squalane.jpg',
      inStockQuantity: 100,
      slug: 'squalane-cleanser',
      description: '150ml',
      price: 25.99,
    },
    {
      _id: 8,
      name: 'Honey Potion Mask',
      image: 'images/honeyPotion.jpg',
      inStockQuantity: 100,
      slug: 'honey-potion-mask',
      description: '100ml',
      price: 13.35,
    },
  ],
};
export default data;
